// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class ghg
{
        public const string achievement_shooterbronze = "CgkI18y_lYISEAIQBg"; // <GPGSID>
        public const string achievement_fighterbronze = "CgkI18y_lYISEAIQAw"; // <GPGSID>
        public const string achievement_fightergold = "CgkI18y_lYISEAIQAQ"; // <GPGSID>
        public const string achievement_champion_gold = "CgkI18y_lYISEAIQCg"; // <GPGSID>
        public const string achievement_shooter_silver = "CgkI18y_lYISEAIQBQ"; // <GPGSID>
        public const string achievement_champion_silver = "CgkI18y_lYISEAIQCw"; // <GPGSID>
        public const string achievement_richiebronze = "CgkI18y_lYISEAIQCQ"; // <GPGSID>
        public const string achievement_fightersilver = "CgkI18y_lYISEAIQAg"; // <GPGSID>
        public const string achievement_richiegold = "CgkI18y_lYISEAIQBw"; // <GPGSID>
        public const string achievement_richiesilver = "CgkI18y_lYISEAIQCA"; // <GPGSID>
        public const string achievement_shootergold = "CgkI18y_lYISEAIQBA"; // <GPGSID>

}

